#!/bin/bash
#cat /sys/class/power_supply/hid-34:88:5d:8d:0c:d7-battery/uevent | grep POWER_SUPPLY_CAPACITY= | grep -o '[[:digit:]]\+'

#BAT0=/sys/class/power_supply/BAT0
#BAT1=/sys/class/power_supply/BAT1
#BAT0_PERCENT=$(cat $BAT0/uevent | grep POWER_SUPPLY_CAPACITY= | grep -o '[[:digit:]]\+')
#BAT1_PERCENT=$(cat $BAT1/uevent | grep POWER_SUPPLY_CAPACITY= | grep -o '[[:digit:]]\+')

OUTPUT="$(cat /sys/class/power_supply/hid-34:88:5d:8d:0c:d7-battery/uevent | grep POWER_SUPPLY_CAPACITY= | grep -o '[[:digit:]]\+')%"
echo $OUTPUT
